---
abstract: 'nagios check for complete email sending'
author:
  - 'Marc Chantreux <khatar@phear.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-Check-Email-Sender
requires:
  Email::Sender::Simple: 0
  Email::Sender::Transport::SMTP: 0
  Email::Simple: 0
  Email::Simple::Creator: 0
  Modern::Perl: 0
  Nagios::Plugin::Simple: 0
  Try::Tiny: 0
  YAML: 0
  autodie: 0
  strict: 0
  warnings: 0
version: 0.0
